layout_spectrum: 0.4943701
color:
  saturation: 0.6846976
  lightness: 0.5982369
  brandStrength: 0.7608916
  rhythmicContrast: 0.6956769
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.4050179
name: Yuliana
